<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Branch;
use Illuminate\Support\Str;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = [
            [
                'name' => 'Lagos Head Office',
                'code' => 'LHO-001',
                'location' => '45 Marina Road, Lagos Island',
                'phone' => '+234-801-234-5678',
                'email' => 'lagos@foodcompany.com',
                'description' => 'Main headquarters and administrative center',
                'country' => 'Nigeria',
                'state' => 'Lagos',
                'city' => 'Lagos',
                'postal_code' => '101001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Abuja Processing Plant',
                'code' => 'ABJ-002',
                'location' => '12 Industrial Layout, Jabi',
                'phone' => '+234-802-345-6789',
                'email' => 'abuja@foodcompany.com',
                'description' => 'Primary food processing and packaging facility',
                'country' => 'Nigeria',
                'state' => 'FCT',
                'city' => 'Abuja',
                'postal_code' => '900001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Port Harcourt Distribution Center',
                'code' => 'PHC-003',
                'location' => '78 Trans Amadi Industrial Layout',
                'phone' => '+234-803-456-7890',
                'email' => 'portharcourt@foodcompany.com',
                'description' => 'Southern region distribution hub',
                'country' => 'Nigeria',
                'state' => 'Rivers',
                'city' => 'Port Harcourt',
                'postal_code' => '500001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Kano Production Facility',
                'code' => 'KAN-004',
                'location' => '23 Sharada Industrial Estate',
                'phone' => '+234-804-567-8901',
                'email' => 'kano@foodcompany.com',
                'description' => 'Northern region production and processing center',
                'country' => 'Nigeria',
                'state' => 'Kano',
                'city' => 'Kano',
                'postal_code' => '700001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Ibadan Regional Office',
                'code' => 'IBD-005',
                'location' => '56 Dugbe-Alawo Road',
                'phone' => '+234-805-678-9012',
                'email' => 'ibadan@foodcompany.com',
                'description' => 'South-west regional coordination center',
                'country' => 'Nigeria',
                'state' => 'Oyo',
                'city' => 'Ibadan',
                'postal_code' => '200001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Enugu Sales Office',
                'code' => 'ENU-006',
                'location' => '34 Ogui Road',
                'phone' => '+234-806-789-0123',
                'email' => 'enugu@foodcompany.com',
                'description' => 'South-east regional sales and marketing',
                'country' => 'Nigeria',
                'state' => 'Enugu',
                'city' => 'Enugu',
                'postal_code' => '400001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Kaduna Warehouse',
                'code' => 'KAD-007',
                'location' => '89 Kachia Road Industrial Area',
                'phone' => '+234-807-890-1234',
                'email' => 'kaduna@foodcompany.com',
                'description' => 'Storage and distribution warehouse',
                'country' => 'Nigeria',
                'state' => 'Kaduna',
                'city' => 'Kaduna',
                'postal_code' => '800001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Benin City Processing Unit',
                'code' => 'BEN-008',
                'location' => '67 Mission Road',
                'phone' => '+234-808-901-2345',
                'email' => 'benin@foodcompany.com',
                'description' => 'Mid-west regional processing facility',
                'country' => 'Nigeria',
                'state' => 'Edo',
                'city' => 'Benin City',
                'postal_code' => '300001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Calabar Export Terminal',
                'code' => 'CAL-009',
                'location' => '12 Export Processing Zone',
                'phone' => '+234-809-012-3456',
                'email' => 'calabar@foodcompany.com',
                'description' => 'Export processing and shipping terminal',
                'country' => 'Nigeria',
                'state' => 'Cross River',
                'city' => 'Calabar',
                'postal_code' => '540001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Jos Cold Storage',
                'code' => 'JOS-010',
                'location' => '45 Bukuru Industrial Layout',
                'phone' => '+234-810-123-4567',
                'email' => 'jos@foodcompany.com',
                'description' => 'Temperature-controlled storage facility',
                'country' => 'Nigeria',
                'state' => 'Plateau',
                'city' => 'Jos',
                'postal_code' => '930001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Owerri Sales Branch',
                'code' => 'OWE-011',
                'location' => '28 Wethedral Road',
                'phone' => '+234-811-234-5678',
                'email' => 'owerri@foodcompany.com',
                'description' => 'Imo state sales office',
                'country' => 'Nigeria',
                'state' => 'Imo',
                'city' => 'Owerri',
                'postal_code' => '460001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Warri Distribution Point',
                'code' => 'WAR-012',
                'location' => '15 Effurun-Sapele Road',
                'phone' => '+234-812-345-6789',
                'email' => 'warri@foodcompany.com',
                'description' => 'Delta state distribution center',
                'country' => 'Nigeria',
                'state' => 'Delta',
                'city' => 'Warri',
                'postal_code' => '332001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Maiduguri Regional Office',
                'code' => 'MAI-013',
                'location' => '42 Baga Road',
                'phone' => '+234-813-456-7890',
                'email' => 'maiduguri@foodcompany.com',
                'description' => 'North-east regional office',
                'country' => 'Nigeria',
                'state' => 'Borno',
                'city' => 'Maiduguri',
                'postal_code' => '600001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Abeokuta Production Unit',
                'code' => 'ABE-014',
                'location' => '19 Adigbe Industrial Estate',
                'phone' => '+234-814-567-8901',
                'email' => 'abeokuta@foodcompany.com',
                'description' => 'Small-scale production facility',
                'country' => 'Nigeria',
                'state' => 'Ogun',
                'city' => 'Abeokuta',
                'postal_code' => '110001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Uyo Processing Center',
                'code' => 'UYO-015',
                'location' => '31 Aka Road',
                'phone' => '+234-815-678-9012',
                'email' => 'uyo@foodcompany.com',
                'description' => 'Akwa Ibom processing center',
                'country' => 'Nigeria',
                'state' => 'Akwa Ibom',
                'city' => 'Uyo',
                'postal_code' => '520001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Makurdi Warehouse',
                'code' => 'MAK-016',
                'location' => '54 North Bank Area',
                'phone' => '+234-816-789-0123',
                'email' => 'makurdi@foodcompany.com',
                'description' => 'Benue state storage facility',
                'country' => 'Nigeria',
                'state' => 'Benue',
                'city' => 'Makurdi',
                'postal_code' => '970001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Sokoto Regional Hub',
                'code' => 'SOK-017',
                'location' => '76 Aliyu Jodi Road',
                'phone' => '+234-817-890-1234',
                'email' => 'sokoto@foodcompany.com',
                'description' => 'North-west regional hub',
                'country' => 'Nigeria',
                'state' => 'Sokoto',
                'city' => 'Sokoto',
                'postal_code' => '840001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Akure Sales Office',
                'code' => 'AKU-018',
                'location' => '22 Oba Adesida Road',
                'phone' => '+234-818-901-2345',
                'email' => 'akure@foodcompany.com',
                'description' => 'Ondo state sales office',
                'country' => 'Nigeria',
                'state' => 'Ondo',
                'city' => 'Akure',
                'postal_code' => '340001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Ilorin Distribution Center',
                'code' => 'ILO-019',
                'location' => '38 Taiwo Road',
                'phone' => '+234-819-012-3456',
                'email' => 'ilorin@foodcompany.com',
                'description' => 'Kwara state distribution center',
                'country' => 'Nigeria',
                'state' => 'Kwara',
                'city' => 'Ilorin',
                'postal_code' => '240001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Bauchi Processing Facility',
                'code' => 'BAU-020',
                'location' => '91 Dass Road Industrial Area',
                'phone' => '+234-820-123-4567',
                'email' => 'bauchi@foodcompany.com',
                'description' => 'Food processing and packaging facility',
                'country' => 'Nigeria',
                'state' => 'Bauchi',
                'city' => 'Bauchi',
                'postal_code' => '740001',
                'timezone' => 'Africa/Lagos',
                'is_active' => true,
            ],
        ];

        foreach ($branches as $branch) {
            Branch::create($branch);
        }

        $this->command->info('✅ 20 branches created successfully.');
    }
}
